DROP TABLE TB_MEMBER;

--번호, 이름, 나이, 성별, 주소, 직업, 전화번호, 이메일
CREATE TABLE TB_MEMBER(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
AGE NUMBER NOT NULL,
GENDER VARCHAR2(2) CHECK(GENDER IN('M','F')) NOT NULL,
LOCATION VARCHAR2(500),
JOB VARCHAR2(300),
TEL VARCHAR2(20),
EMAIL VARCHAR2(100)
);

INSERT INTO TB_MEMBER
VALUES(1, '강사', 100, 'M', '서울시 강남구','선생님', '010-1234-5678', 'TEACHER@TEACHER.COM');

SELECT NO, NAME, AGE, GENDER, LOCATION, JOB, TEL, EMAIL
FROM TB_MEMBER;